version: 2
models:
  - name: customers
    description: this  model will provide a comprehsnive customer informartion for analysis.
    columns:
      - name: cust_id
        description: this  model will provide a comprehsnive customer informartion for analysis.
        tests:
          - unique:
          - not_null:
          - accpted_values:
            values: ['value']
          - relationships:
                to: ref('model_name')          
                field: field_name





    